# Generated by Django 5.1.6 on 2025-04-10 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anpr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedvideo',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='uploadedvideo',
            name='output_excel',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='uploadedvideo',
            name='detected_text',
            field=models.TextField(default='No text detected'),
        ),
    ]
